"""V2.1. add to race_rider: start_time, finish_time, pi_offset_time

Revision ID: 3dcbd3b3fc33
Revises: 22368d8bf592
Create Date: 2025-11-27 10:39:28.269873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dcbd3b3fc33'
down_revision: Union[str, Sequence[str], None] = '22368d8bf592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_riders') as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('finish_time', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('pi_offset_time', sa.Integer(), nullable=True))

    # op.add_column('race_riders', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    # op.add_column('race_riders', sa.Column('finish_time', sa.DateTime(timezone=True), nullable=True))
    # op.add_column('race_riders', sa.Column('pi_offset_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race_riders', 'pi_offset_time')
    op.drop_column('race_riders', 'finish_time')
    op.drop_column('race_riders', 'start_time')
    # ### end Alembic commands ###
