"""test change 2

Revision ID: 42d8ad9b95fa
Revises: 0001_processed_flags_unique_idx
Create Date: 2025-10-14 16:08:44.352724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d8ad9b95fa'
down_revision: Union[str, Sequence[str], None] = '0001_processed_flags_unique_idx'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("points") as batch_op:
        batch_op.create_unique_constraint("ux_points_device_time", ["device_id", "t_epoch"])

    # op.drop_index(op.f('ux_points_device_time'), table_name='points')
    # op.create_unique_constraint('ux_points_device_time', 'points', ['device_id', 't_epoch'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux_points_device_time', 'points', type_='unique')
    op.create_index(op.f('ux_points_device_time'), 'points', ['device_id', 't_epoch'], unique=1)
    # ### end Alembic commands ###
