"""baseline schema

Revision ID: 438e4bd69220
Revises: 
Create Date: 2026-03-23 17:44:57.717991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '438e4bd69220'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingest_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at_epoch', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at_epoch', sa.Integer(), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_raw_device_id'), 'ingest_raw', ['device_id'], unique=False)
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('t_epoch', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('ele', sa.Float(), nullable=True),
    sa.Column('sog', sa.Float(), nullable=True),
    sa.Column('cog', sa.Float(), nullable=True),
    sa.Column('fx', sa.Integer(), nullable=True),
    sa.Column('hdop', sa.Float(), nullable=True),
    sa.Column('nsat', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at_epoch', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 't_epoch', name='ux_points_device_time')
    )
    op.create_index(op.f('ix_points_device_id'), 'points', ['device_id'], unique=False)
    op.create_index(op.f('ix_points_t_epoch'), 'points', ['t_epoch'], unique=False)
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starts_at_epoch', sa.Integer(), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at_epoch', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('bike', sa.String(length=128), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('team', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('geojson', sa.Text(), nullable=True),
    sa.Column('gpx', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_race_id'), 'route', ['race_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'name', name='ux_route_category_name')
    )
    op.create_index(op.f('ix_categories_route_id'), 'categories', ['route_id'], unique=False)
    op.create_table('leaderboard_cache',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('etag', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_epoch', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('leaderboard_hist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('official_pdf', sa.LargeBinary(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_epoch', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_hist_category_id'), 'leaderboard_hist', ['category_id'], unique=False)
    op.create_table('race_riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('comm_setting', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('recording', sa.Boolean(), nullable=False),
    sa.Column('start_time_rfid', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_time_rfid_epoch', sa.Integer(), nullable=True),
    sa.Column('start_time_pi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_time_pi_epoch', sa.Integer(), nullable=True),
    sa.Column('finish_time_rfid', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_time_rfid_epoch', sa.Integer(), nullable=True),
    sa.Column('finish_time_pi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_time_pi_epoch', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_riders_category_id'), 'race_riders', ['category_id'], unique=False)
    op.create_index(op.f('ix_race_riders_device_id'), 'race_riders', ['device_id'], unique=False)
    op.create_index(op.f('ix_race_riders_rider_id'), 'race_riders', ['rider_id'], unique=False)
    op.create_table('track_cache',
    sa.Column('race_rider_id', sa.Integer(), nullable=False),
    sa.Column('geojson', sa.Text(), nullable=True),
    sa.Column('etag', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_epoch', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_rider_id'], ['race_riders.id'], ),
    sa.PrimaryKeyConstraint('race_rider_id')
    )
    op.create_table('track_hist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_rider_id', sa.Integer(), nullable=False),
    sa.Column('geojson', sa.Text(), nullable=True),
    sa.Column('gpx', sa.Text(), nullable=True),
    sa.Column('raw_txt', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_epoch', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_rider_id'], ['race_riders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_hist_race_rider_id'), 'track_hist', ['race_rider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_hist_race_rider_id'), table_name='track_hist')
    op.drop_table('track_hist')
    op.drop_table('track_cache')
    op.drop_index(op.f('ix_race_riders_rider_id'), table_name='race_riders')
    op.drop_index(op.f('ix_race_riders_device_id'), table_name='race_riders')
    op.drop_index(op.f('ix_race_riders_category_id'), table_name='race_riders')
    op.drop_table('race_riders')
    op.drop_index(op.f('ix_leaderboard_hist_category_id'), table_name='leaderboard_hist')
    op.drop_table('leaderboard_hist')
    op.drop_table('leaderboard_cache')
    op.drop_index(op.f('ix_categories_route_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_route_race_id'), table_name='route')
    op.drop_table('route')
    op.drop_table('riders')
    op.drop_table('races')
    op.drop_index(op.f('ix_points_t_epoch'), table_name='points')
    op.drop_index(op.f('ix_points_device_id'), table_name='points')
    op.drop_table('points')
    op.drop_index(op.f('ix_ingest_raw_device_id'), table_name='ingest_raw')
    op.drop_table('ingest_raw')
    op.drop_table('devices')
    # ### end Alembic commands ###
