"""race_rider: added a start and finish time for the pi and rfid

Revision ID: 937d6fe1d835
Revises: 3dcbd3b3fc33
Create Date: 2025-12-01 13:33:36.870813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937d6fe1d835'
down_revision: Union[str, Sequence[str], None] = '3dcbd3b3fc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_riders') as batch_op:
        batch_op.add_column(sa.Column('start_time_rfid', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('start_time_pi', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('finish_time_rfid', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('finish_time_pi', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('start_time')
        batch_op.drop_column('finish_time')
        batch_op.drop_column('pi_offset_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race_riders', sa.Column('pi_offset_time', sa.INTEGER(), nullable=True))
    op.add_column('race_riders', sa.Column('finish_time', sa.DATETIME(), nullable=True))
    op.add_column('race_riders', sa.Column('start_time', sa.DATETIME(), nullable=True))
    op.drop_column('race_riders', 'finish_time_pi')
    op.drop_column('race_riders', 'finish_time_rfid')
    op.drop_column('race_riders', 'start_time_pi')
    op.drop_column('race_riders', 'start_time_rfid')
    # ### end Alembic commands ###
