"""Category: added name, unique constraint on name and route_id 

Revision ID: 22368d8bf592
Revises: 42d8ad9b95fa
Create Date: 2025-11-06 13:42:00.148140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22368d8bf592'
down_revision: Union[str, Sequence[str], None] = '42d8ad9b95fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', recreate='auto') as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint('ux_route_category_name', ['route_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', recreate='auto') as batch_op:
        batch_op.drop_constraint('ux_route_category_name', type_='unique')
        batch_op.drop_column('name')
    # ### end Alembic commands ###
