"""track_hist: add raw_txt col

Revision ID: bf71d77a9db6
Revises: 937d6fe1d835
Create Date: 2025-12-01 13:47:49.518930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf71d77a9db6'
down_revision: Union[str, Sequence[str], None] = '937d6fe1d835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_hist', sa.Column('raw_txt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_hist', 'raw_txt')
    # ### end Alembic commands ###
