"""
Transactional email helpers for authentication flows.

Resend is used only for password-reset emails in the current auth plan. Signup
email verification is intentionally not enabled.
"""

from urllib.parse import quote

import resend

from src.utils.env import required_env


def build_password_reset_url(raw_token: str) -> str:
    """
    Build the public password-reset URL for a raw reset token.

    Input Args:
      raw_token: raw token generated by src.auth.tokens.create_auth_token.

    Output:
      Fully-qualified reset URL using APP_PUBLIC_BASE_URL.

    Notes:
      The base URL comes from trusted environment configuration, not from the
      inbound request host.
    """
    base_url = required_env("APP_PUBLIC_BASE_URL", "password reset URL building").rstrip("/")
    safe_token = quote((raw_token or "").strip(), safe="")
    if not safe_token:
        raise RuntimeError("raw_token is required to build a password reset URL.")
    return f"{base_url}/reset-password/{safe_token}"


def send_email(to: str, subject: str, html: str):
    """
    Send one transactional email through Resend.

    Input Args:
      to: recipient email address.
      subject: email subject line.
      html: email HTML body.

    Output:
      Resend API response.

    Notes:
      This function never prints the API key. Callers should also avoid logging
      reset links because they contain the raw token.
    """
    resend.api_key = required_env("RESEND_API_KEY", "auth email sending")
    mail_from = required_env("MAIL_FROM", "auth email sending")
    recipient = (to or "").strip()
    if not recipient:
        raise RuntimeError("Email recipient is required.")

    params: resend.Emails.SendParams = {
        "from": mail_from,
        "to": [recipient],
        "subject": subject,
        "html": html,
    }
    return resend.Emails.send(params)


def send_password_reset_email(user, raw_token: str):
    """
    Send a password-reset link to a user account email address.

    Input Args:
      user: User row with an email address.
      raw_token: raw password-reset token to include in the reset link.

    Output:
      Resend API response from send_email.
    """
    reset_url = build_password_reset_url(raw_token)
    subject = "Reset your Kooksnylive password"
    html = f"""
    <p>You requested a password reset for your Kooksnylive account.</p>
    <p><a href="{reset_url}">Reset your password</a></p>
    <p>This link will expire soon. If you did not request this, you can ignore this email.</p>
    """
    return send_email(user.email, subject, html)
